Fix issue compiling with uclibc
uClibc version: uclibc-ng-1.0.24

```
In file included from ./hhu/build-arm/ejdb2/src/ejdb2-build/src/extern_iowow/src/platform/iwp.c:43:0:
./hhu/build-arm/ejdb2/src/ejdb2-build/src/extern_iowow/src/platform/unix/unix.c: In function ‘_iwp_fstat’:
./hhu/build-arm/ejdb2/src/ejdb2-build/src/extern_iowow/src/platform/unix/unix.c:103:33: error: ‘struct stat’ has no member named ‘st_atim’
   fs->atime = _IW_TIMESPEC2MS(st.st_atim);
                                 ^
./hhu/build-arm/ejdb2/src/ejdb2-build/src/extern_iowow/src/platform/unix/unix.c:54:35: note: in definition of macro ‘_IW_TIMESPEC2MS’
 #define _IW_TIMESPEC2MS(IW_ts) (((IW_ts).tv_sec * 1000ULL) + (uint64_t) round((IW_ts).tv_nsec / 1.0e6))
                                   ^
compilation terminated due to -Wfatal-errors.
```